version: '3.8'

services:
  tts:
    build: ./tts-service
    ports:
      - "${TTS_PORT:-8082}:8082"
    environment:
      - MODEL_NAME=${MODEL_TTS:-tts_models/en/ljspeech/tacotron2-DDC}
    volumes:
      - models_tts:/opt/models
      - logs:/var/log/app
    networks:
      - speech_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  asr:
    build: ./asr-service
    ports:
      - "${ASR_PORT:-8081}:8081"
    environment:
      - MODEL_NAME=${MODEL_ASR:-base.en}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
    volumes:
      - models_asr:/opt/models
      - logs:/var/log/app
    networks:
      - speech_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT:-8000}:8000"
    environment:
      - TTS_URL=http://tts:8082
      - ASR_URL=http://asr:8081
    volumes:
      - logs:/var/log/app
    networks:
      - speech_net

volumes:
  models_tts:
  models_asr:
  logs:

networks:
  speech_net:
    driver: bridge